### PR TITLE
Converting GEOS sea-ice restart file into Soca restart file

### PR DESCRIPTION
**Pull request by mjkagnes123**

### CODE REVIEW

**Comment by mathomp4** [comment]
Paging @guillaumevernieres

**Comment by guillaumevernieres** [comment]
@mjkagnes123 : 
- Please add a detailed description of your work.
- I presume Eric maintains that part of the GEOS repository, add him (@ehackert) as a reviewer
- Bin Zhao should probably be aware of this work as well

**Comment by mathomp4** [comment]
@guillaumevernieres Random aside: but would like to be added to the GEOS-ESM Org as an Outside Collaborator?

**Comment by yvikhlya** [comment]
I am not sure if it is proper to commit SOCA related stuff into UMD_Etc repo. Are not these different systems?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Random aside: but would like to be added to the GEOS-ESM Org as an Outside Collaborator?

@mathomp4 Sure.

**Comment by guillaumevernieres** [comment]
> I am not sure if it is proper to commit SOCA related stuff into UMD_Etc repo. Are not these different systems?

@yvikhlya , that seems reasonable. I'll let you (the GMAO) decide where you want to move that work.

**Comment by yvikhlya** [comment]
> > I am not sure if it is proper to commit SOCA related stuff into UMD_Etc repo. Are not these different systems?
> 
> @yvikhlya , that seems reasonable. I'll let you (the GMAO) decide where you want to move that work.

I think @ehackert and @mjkagnes123 should consult with SI team on whether it is worth to create a new repo for SOCA code or use the existing repo.

**Comment by yvikhlya** [comment]
@ehackert @mjkagnes123 @mathomp4 Please, keep in mind that this version of UMD_Etc is very old and probably not working, since I did not merge any updates from the S2Sv3.

**Review by tclune — APPROVED** [review]
CMake changes are fine.

**Comment by sanAkel** [comment]
> @ehackert @mjkagnes123 @mathomp4 Please, keep in mind that this version of UMD_Etc is very old and probably not working, since I did not merge any updates from the S2Sv3.

When was this last tested?

**Comment by yvikhlya** [comment]
> > @ehackert @mjkagnes123 @mathomp4 Please, keep in mind that this version of UMD_Etc is very old and probably not working, since I did not merge any updates from the S2Sv3.
> 
> When was this last tested?

I don't think it was ever tested.

**Comment by sanAkel** [comment]
@mjkagnes123 have committed files in this PR in a different, repo, e.g., JCSDA repo, say SOCA?

**Comment by guillaumevernieres** [comment]
> @mjkagnes123 have committed files in this PR in a different, repo, e.g., JCSDA repo, say SOCA?

No. Can you let us know if you are OK or not with that file in the GEOS repo? If not @mjkagnes123 will move it somewhere else.

**Comment by sanAkel** [comment]
In that case are okay as a __placeholder__.

In principle code in this PR has no relationship with _existing_ code, which as we can see has not been even tested. 

Ideally would you (@guillaumevernieres) or @mjkagnes123 please find a place/repo in your org for this work?

**Comment by guillaumevernieres** [comment]
> In that case are okay as a **placeholder**.
> 
> In principle code in this PR has no relationship with _existing_ code, which as we can see has not been even tested.
> 
> Ideally would you (@guillaumevernieres) or @mjkagnes123 please find a place/repo in your org for this work?

OK, my bad. I was under the impression that the GMAO ocean DA code base was maintained in this repository. We could have shared some of the utilities, but since nobody is actually maintaining it, we will migrate what we need in a different place.

**Comment by mjkagnes123** [comment]
Developments related to this PR were included in PR #208.

**Pull request closed without merging**
